# Generated by Django 2.2.4 on 2022-06-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='users_like',
            field=models.ManyToManyField(related_name='books_like', to='lip_app.Users'),
        ),
    ]
